### ISSUE TITLE
No data for this test / Undefined language string

### ISSUE THREAD

**Issue by Virinum** [zonemaster/zonemaster#918] opened 2021-01-05 08:10 UTC
Since a few weeks I get this error.

Tested domain: any (e.g. google.com)

![screenshot](https://user-images.githubusercontent.com/42373861/103620728-518cae80-4f34-11eb-97ee-7d9c98e47d73.png)

Request payload:
```json
{
    "jsonrpc": "2.0",
    "id": 1609833332863,
    "method": "get_test_results",
    "params": {
        "id": "4d1324661ad4be68",
        "language": "de"
    }
}
```

**Comment by matsduf** [comment] 2021-01-05 08:29
The request payload that you quote says `"language": "de"`, but we do not yet have any support for German (but we would love to have that). This could be some "private" installation with German translation, but in that case, Zonemaster-Backend is not correctly configured. The official GUI would not send "de" as language string, so I assume that this is a "private" installation.

Please provide some more details that you have. What versions of Zonemaster does GUI report?

**Comment by Virinum** [comment] 2021-01-05 08:40
It's not a private installation. It's the official site https://zonemaster.net/

I've tested with Chrome and Firefox on Windows 10 (also in private mode) and with Safari on iOS 14 (also in private mode). All show the same behavior.

**Comment by matsduf** [comment] 2021-01-05 08:54
I cannot replicate your problem. What language do you select before you test? If you follow the link  https://zonemaster.net/result/db4946643ec264ff do you see any problem? If you then change languages?

**Comment by Virinum** [comment] 2021-01-05 09:16
I don't select any language. English as default would be finde.

I've recorded a small video. Hope it helps.

https://user-images.githubusercontent.com/42373861/103628150-ded50080-4f3e-11eb-8c0f-f332311a0b01.mp4

**Comment by matsduf** [comment] 2021-01-05 09:56
@Virinum, do you have your web browsers in German? Is the locale set to "de_XX"? It seems to be that the Zonemaster-GUI follows the browser language, and that might be the cause.

**Comment by Virinum** [comment] 2021-01-05 10:22
Yes, all my systems and web browsers are in German.
The `Accept-Language` headers are the following:
- Safari on iOS 14: `de-de`
- Chrome on Windows 10: `de,de-DE;q=0.9,en-US;q=0.8,en;q=0.7`
- Firefox on Windows 10: `de,en-US;q=0.7,en;q=0.3`

**Comment by pnax** [comment] 2021-01-05 11:18
I can reproduce when switching my browser to a language unsupported by Zonemaster.
This looks like a bug in the GUI. I have a look into it

**Comment by matsduf** [comment] 2021-01-05 13:06
@Virinum, thank you very much for the report and many details. We can confirm that this is a bug in Zonemaster-GUI, and we have created an issue in that repository and will try to resolve it.

I will close this issue. It is not resolved, but we refer till https://github.com/zonemaster/zonemaster-gui/issues/168 instead.

**Closed by matsduf** 2021-01-05 13:06 UTC
Labels: T-Question

**Comment by pnax** [comment] 2021-01-05 13:23
While waiting for a fix, I can suggest the following workaround : explicitly change the language twice in the web interface, for instance choose "Danish" then "English" again in the header (under the burger menu on the mobile interface), this should properly reload the results.

**Comment by Virinum** [comment] 2021-01-05 13:47
Alright. Thank you!
When I find some time I'll try to work on a german translation.

**Comment by matsduf** [comment] 2021-01-05 14:09
> When I find some time I'll try to work on a german translation.

That would be great! Create an issue or drop us a line when you are ready. We have detailed instructions for translators.
