### ISSUE TITLE
RFC8080 Support

### ISSUE THREAD

**Issue by andreasschulze** [zonemaster/zonemaster#796] opened 2019-08-06 09:53 UTC
just a friendly reminder:

currently (08/2019) zonemaster.net could not handle ed25519 keys.
such keys are reported as "Unknown cryptographic algorithm"

example: https://zonemaster.net/result/573794bafe9988b1

**Comment by mattias-p** [comment] 2019-08-07 12:20
Thanks for showing interest! It can make a difference when we prioritize what to work on.

Closing this as a duplicate of zonemaster/zonemaster-engine#564.

**Closed by mattias-p** 2019-08-07 12:20 UTC
