### ISSUE TITLE
Update system testing documentation

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster#631] opened 2018-05-23 09:32 UTC
System testing is an important part of the release process. The current [system testing documentation](https://github.com/zonemaster/zonemaster/blob/master/docs/internal-documentation/maintenance/SystemTesting.md) is decent but it should be updated to reflect changes in our practices since it was written.

The document should be an up to date description of the task of testing that we perform in preparation of each release.

**Comment by mattias-p** [comment] 2019-06-03 10:12
When making this update, mind that the link structure of the Backend installation instruction has changed. Now it has separate sections for configuration and startup for each operating system. The links from the system testing documentation needs to be updated accordingly.

**Comment by matsduf** [comment] 2019-11-13 14:47
Fixed by the PRs.

**Comment by mattias-p** [comment] 2019-11-20 10:25
@matsduf Do you really think the system testing documentation is up to date with our current practices?

**Comment by matsduf** [comment] 2019-11-20 10:32
@mattias-p, that is a hard question, but we agreed on the F2F to consider this issue to be fixed. The issue is vague so only you can fix it, or specify. And set a milestone on it.

**Comment by mattias-p** [comment] 2019-11-20 15:37
@matsduf I've updated the issue description.

**Closed** 2023-11-30 07:31 UTC
Labels: A-Documentation
