### ISSUE TITLE
Files missing while running make distcheck

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster#627] opened 2018-05-11 07:52 UTC
```
sandoche@sandoche:~/ZM-testing/zonemaster-ldns$ make distcheck
"/usr/bin/perl" "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck
No such file: META.yml
Not in MANIFEST: LDNS.bs
```

**Comment by mattias-p** [comment] 2018-05-14 13:26
This is really two issues.

1. **No such file: META.yml**
    I meant to remedy this problem in dotse/zonemaster-ldns#52 but apparently I wasn't thorough enough in my testing and what I committed wasn't the real fix. Instead the real fix is installing Module::Install as a dist-time dependency.
    Since Module::Install is a requirement when creating the dist tarballs, the instruction to install it should be added to the release process document. However I'm not sure under which section such a step fits in. Maybe a new heading is mandated?
2. **Not in MANIFEST: LDNS.bs**
    I've failed to reproduce this. Can you provide more details on how you end up in this state?

**Comment by sandoche2k** [comment] 2018-05-14 14:00
In Ubuntu 16.04.4 LTS, while making make distcheck
```
"/usr/bin/perl" "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck
No such file: META.yml
Not in MANIFEST: LDNS.bs
```

**Comment by matsduf** [comment] 2018-05-14 14:27
I just tested on an Ubuntu 16.04.4 server. I checkout the develop branch, in sync with the repo on Github. I followed the ReleaseProcess document, but I did not run into your issue:

```
$ git status --ignored
On branch develop
nothing to commit, working directory clean

$ mkdir -p inc/.author 

$ perl Makefile.PL
include /home/matsd/git/zonemaster-ldns/inc/Module/Install.pm
include inc/Module/Install/Metadata.pm
include inc/Module/Install/Base.pm
include inc/Module/Install/Makefile.pm
include inc/Module/Install/XSUtil.pm
include inc/Module/Install/Can.pm
Writing ppport.h
Feature internal ldns enabled
Feature idn enabled
Feature randomized capitalization disabled
include inc/Module/Install/WriteAll.pm
include inc/Module/Install/Win32.pm
include inc/Module/Install/Fetch.pm
Checking if your kit is complete...
Warning: the following files are missing in your kit:
	META.yml
Please inform the author.
Generating a Unix-style Makefile
Writing Makefile for Zonemaster::LDNS
Writing MYMETA.yml and MYMETA.json
Writing META.yml

$ make all
(Output omitted)

$ make distcheck
"/usr/bin/perl" "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck

$ 
```

**Closed** 2019-01-18 14:40 UTC
